- repo/pyproject.toml
- signer/pyproject.toml
* click: use release version
* tuf: use release version
* securesystemslib: pin a git hash (latest release does not have azurekms which we want)
> Pin more python dependencies

- .github/workflows/release.yml
- docs/RELEASE.md
Three steps:
* build signer
* Make signer release to pypi
* Make overall release on GitHub
This means at the moment signer and repository releases are tied to each other.
The release environment has been created: deployment requires approval from one of [jku, kommendorkapten, lukpueh].
The PyPI Trusted Publishing setup is "pending": it should become an actual setup on first release.
I have tested this (except for the pypi publishing part: that can only succeed on the upstream project)
> workfows: Add release.yml

- docs/CHANGELOG.md
* Signer release is not happening yet
* Add info on upgrading an existing release
First item was only realized after release, second should have been included in the release already but was forgotten.
> Update Changelog after release

- signer/test/test_user.py
- signer/tuf_on_ci_sign/_common.py
- signer/tuf_on_ci_sign/_signer_repository.py
- signer/tuf_on_ci_sign/_user.py
- signer/tuf_on_ci_sign/delegate.py
- signer/tuf_on_ci_sign/sign.py
- tox.ini
* better code structure
* ability to configure signing systems in `.tuf-on-ci-sign.ini`
Refactoring:
* Separate a _user module with a User class
* New class manages the users signers and configuration
* Design would allow User class to write the config (it does not currently)
New feature:
* privkeyuris can now be included in the configuration. These uris will then be used when signing. Example:
```
[signing-keys]
762cb22caca65de5e9b7b6baecb84ca989d337280ce6914b6440aea95769ad93 = hsm:2?label=YubiKey+PIV+%2315835999
```
The obvious next steps would be to automatically write the privkeyuris to the config when user becomes a signer. Technically this is possible to add already but I'm trying to keep the PR limited...
> signer: Refactor user configuration

- repo/tuf_on_ci/_repository.py
- repo/tuf_on_ci/snapshot.py
- signer/pyproject.toml
- signer/tuf_on_ci_sign/__init__.py
- signer/tuf_on_ci_sign/import_repo.py
@kommendorkapten not sure if this is too late for you but... `tuf-on-ci-import-repo <EVENT> [<IMPORTDATA>]` will import
* legacy playground repos
* generic tuf repositories (when given additional import configuration file which the tool can pre-generate)
This is a draft since 
* it's quite untested
* I'm unsure if adding something like this into the core code base is smart: it's just 200 lines but it's unlikely to get tested well as it will be only ran a few times
* needs documentation that explains the steps of importing
* create a repository with the original metadata in the expected place
* add workflows from tuf-on-ci-template
* setup signer tool locally
* handle unsupported keys somehow
* run tuf-on-ci-import-repo to start a signing event
still, I think it's surprisingly self …
> signer: Add import tool

- signer/create-config-file.sh
This fixes a small typo found in `signer/create-config-file.sh` when the script checks the homebrew directory for `libykcs11.dylib`.
> Fix small typo in the signer create-config-file script

- .github/workflows/ci.yml
- .github/workflows/release.yml
- actions/offline-version-bump/action.yml
- actions/online-version-bump/action.yml
- actions/signing-event/action.yml
- actions/snapshot/action.yml
Minor changes only:
https://github.com/actions/checkout/blob/main/CHANGELOG.md
Add version number as a comment, dependabot should now update it.
> build(deps): bump actions/checkout from 3.5.3 to 3.6.0

- signer/tuf_on_ci_sign/_signer_repository.py
When a signer (or multiple) are being removed, the resulting list of signers will not always be correct, as the list being iterated over is mutated during the iteration.
> Fixed a bug that causes incorrect management of keys.

- repo/pyproject.toml
- signer/pyproject.toml
- signer/tuf_on_ci_sign/_common.py
- signer/tuf_on_ci_sign/_signer_repository.py
- tests/e2e.sh
- tests/expected/delegated/metadata/1.delegated.json
- tests/expected/delegated/metadata/1.root.json
- tests/expected/delegated/metadata/2.snapshot.json
- tests/expected/delegated/metadata/2.targets.json
- tests/expected/delegated/metadata/timestamp.json
This ballooned a bit (but code is actually removed, the added lines are tests and test expected results).
* Update to securesystemslib 0.30
* This means we don't need a specific sigstore version anymore (in practice we get sigstore 2.0)
* Use the improved sigstore signer import (or "identity registration") in securesystemslib
* Fix a bug related to delegated roles that I found while testing the above
* Add a test for the bug
This should enable us to finally make a PyPI release of tuf-on-ci-signer.
Fixes #88
Fixes #42
Enables fixing #31
> Update dependencies (securesystemslib, sigstore)

- actions/upload-repository/action.yml
When publishing, the targets was moved to /artifacts insteaf of /targets if not specified. As this is a breaking change we should revert that.
> Revert change of artifats path to targets.

- docs/CHANGELOG.md
- repo/pyproject.toml
- signer/pyproject.toml
* My intuition says to not wait for #96 and instead do another release soon
* this should be the first pypi release: possible issues in the publishing pipeline there might lead to needing new releases soon as well
> Release v0.1.0

- actions/create-signing-events/action.yml
- actions/online-sign/action.yml
- actions/signing-event/action.yml
- actions/upload-repository/action.yml
- repo/tuf_on_ci/status.py
Closes https://github.com/theupdateframework/tuf-on-ci/issues/79
Also this PR tries do detect updates on remote when running `tuf-on-ci-status`. If there are updates on remote, it wont print out the complete error message from git, instead it prints out that there are updates on remote, and so will not try to push.
As there are updates on remote, those updates will trigger a new workflow run that exectues `tuf-on-ci-status`, so it's safe to just ignore this error.
> Adds step summaries for the most important steps

- docs/CHANGELOG.md
- repo/pyproject.toml
- signer/pyproject.toml
Bug fix release. signer actually has no changes but the release process currently can't handle not releasing signer as well so both get a version bump.
> Release v0.2.0

- actions/online-sign/action.yml
- actions/upload-repository/action.yml
Closes https://github.com/theupdateframework/tuf-on-ci/issues/126
This is 1/2 PRs, the other is against the template repo as it contains an update to the workflow.
During the online sign action, the produced commit is saved, and passed as an input parameter to the deploy workflow. The deploy workflow uses this ref when checking out the repository. This ref can also be set during manual invocation of the publish workflow. If nothing is provided the mos recent commit is used (the default behaviour in the checkout action).
If the commit from the signing action is not reachable (i.e due to a delay in GitHub) the checkout action fails, and abort the deployment. This is an actionable event and the action can so be re-run.
An example signing: …
> Verify that correct version is published.

- README.md
- actions/online-sign/action.yml
- docs/ONLINE-SIGNING-SETUP.md
- docs/REPOSITORY-MAINTENANCE.md
- repo/pyproject.toml
- signer/pyproject.toml
- signer/tuf_on_ci_sign/delegate.py
- tests/e2e.sh
Fixes #117.
Adds support for AWS KMS, which was basically already there due to the AWSSigner class from securesystemslib.
This PR adds support to tuf-on-ci-delegate for setting up online signing to use AWS KMS. As part of this we need to pass the scheme for the key, see https://github.com/secure-systems-lab/securesystemslib/issues/668. I've made this a multiple choice, displaying the schemes as AWS names them.
I also added an AWS auth step to the online signing action, just like the Google one. I saw there was some discussion on whether this is right way to go in #56, I think it's fine but welcome other thoughts. I'll be happy to look at switching Azure over to match too.
Tested over at https://github.com/jonnystoten/tuf-testing
> Add support for AWS KMS

- signer/pyproject.toml
git dependencies are not allowed on PyPI so I don't see us ever using them: remove the hatchling config for that.
> Cleanup in pyproject.toml

- actions/create-signing-events/action.yml
- actions/online-sign/action.yml
- actions/signing-event/action.yml
- docs/CHANGELOG.md
- docs/DEVELOPMENT.md
- docs/REPOSITORY-MAINTENANCE.md
- repo/pyproject.toml
- repo/tuf_on_ci/__init__.py
- repo/tuf_on_ci/_repository.py
- repo/tuf_on_ci/signing_event.py
- tests/e2e.sh
This PR adds support for a custom GitHub token. The idea is to keep the default GitHub token as a low-permission one (so other workflows don't operate on a high permission token unnecessarily) and to add a fine grained token with higher permissions into repository secrets.
Implementation requires some workarounds to support both default and custom tokens (see dispatching discussion below) and a bit of refactoring (see python command splitting). See docs/REPOSITORY-MAINTENANCE.md changes for documentation.
This is going to require users to modify their workflows (or rather copy the workflows from tuf-on-ci-template) on upgrade as the actions now require a token argument.
* `tuf-on-ci-status` command was previously provided by the `status` module. Refactor so that there is a `signing_event` …
> Support custom GitHub tokens

- repo/tuf_on_ci/create_signing_events.py
- repo/tuf_on_ci/online_sign.py
- repo/tuf_on_ci/signing_event.py
- signer/tuf_on_ci_sign/delegate.py
- signer/tuf_on_ci_sign/import_repo.py
- signer/tuf_on_ci_sign/sign.py
All commits done by signer and repository will now include Signed-Off-By. This makes DCO check happy based on tests in https://github.com/jku/yet-another-test-repo/
I didn't want to make this configurable (because it covers both repository and signer and would be a bit of a pain to manage): hopefully enabling Signed-Off-By for everyone will:
* not be too annoying for people who don't care about signoff
* fix the problem for orgs that require it
> repo/signer: Add Signed-Off-By to all commits

- actions/test-repository/action.yml
- client/README.md
- repo/pyproject.toml
- repo/tuf_on_ci/__init__.py
- repo/tuf_on_ci/client.py
This adds an action that runs a basic client against the repository  
The action could be used in
* cron workflow
* publish workflow
Fixes #38 (at least parts of it)
> Add a smoke test for published repository

- actions/create-signing-events/action.yml
- actions/online-sign/action.yml
- actions/signing-event/action.yml
- actions/test-repository/action.yml
- actions/update-issue/action.yml
- actions/upload-repository/action.yml
- signer/tuf_on_ci_sign/_signer_repository.py
Open and close issues based on workflow successes:
* If a TUF-on-CI workflow fails and issue does not exist, file an issue
* If issue for the workflow exists, add a comment
* If a TUF-on-CI workflow succeeds and issue exists for workflow, close issue
Some notes:
* I've kept this spartan on purpose: we may want some configurability but I'd rather do that based on actual user feedback
* Companion template PR: https://github.com/theupdateframework/tuf-on-ci-template/pull/17-- please review that one as part of this PR review (leave comments in either one)
* example run: https://github.com/jku/tuf-on-ci-sigstore-test/issues/20
* I'm not happy about how much this complicates the workflows but I don't see better alternatives, see https://docs.google.com/document/d/1syzgpkOFbo3npLLIVnuKEFUZHVR3B92 …
> feature: Add integrated issue handling

- actions/signing-event/action.yml
(PR moved from playground)
Former is arguably the correct choice (search API is global, not project specific) and we have seen at least one case where the search API did not have the content that was already available in repos API and this lasted for a few hours.
Differences:
* new API lists only open issues by default
* new API does not allow filtering by issue type (so we theoretically could find PRs too): I don't think this is an issue as the PRs do not get a label automatically and we are searching based on label
> actions: Use repos API instead of search API

- signer/tuf_on_ci_sign/_signer_repository.py
- tox.ini
ruff now does formatting as well and it does a decent job:
* We can get rid of one more dependency
* linting now takes a whole 0.28 seconds
> Switch from black to ruff

- actions/signing-event/action.yml
- docs/CHANGELOG.md
- docs/REPOSITORY-MAINTENANCE.md
- docs/SIGNER-MANUAL.md
- repo/tuf_on_ci/signing_event.py
- tests/README.md
Pull requests make more sense for the signing event:
* Since there is a branch associated with the signing event, PR matches that better than issue
* The UI is better as the commits are now visible in between the comments
The issue of course is that a signing event can spend a while in a state when it's not ready for merging or even review. This is manageable because:
* we can manage the draft state: the PR is a draft until the signing event is ready
* The check is now visible and useful: it's very clear if the signing event is "green" or not
The main annoyance in this PR is the use of GraphQL to modify draft state. I decided to do that instead of the other options listed in the linked issue discussion. The best alternative would be to rely more on bash and to use `gh` tool as an API. I …
> Use PRs instead of issues for signing events

- docs/CHANGELOG.md
- docs/REPOSITORY-MAINTENANCE.md
This updates the docs to match current requirements.
This is written with the assumption that custom token users do not need the "Allow GHA to create PRs" check: we will see if this is correct.
Fix #188
> Update docs on PR permissions

- docs/SIGNER-SETUP.md
- signer/tuf_on_ci_sign/_user.py
This is not optimal from a security perspective (just blindly looking for modules to dynamically load) but
* the probed locations are all system locations (not user installable)
* this makes the setup process much easier
* it's still possible to set `pykcs11lib`
> signer: Try to guess where libykcs11 could be

- repo/pyproject.toml
- repo/test/test_ci_repository.py
- repo/tuf_on_ci/_repository.py
- repo/tuf_on_ci/create_signing_events.py
- repo/tuf_on_ci/online_sign.py
- repo/tuf_on_ci/signing_event.py
- signer/pyproject.toml
- signer/tuf_on_ci_sign/_common.py
- signer/tuf_on_ci_sign/_signer_repository.py
- signer/tuf_on_ci_sign/_user.py
- signer/tuf_on_ci_sign/delegate.py
- tox.ini
Enable more linter rulesets. This list is not complete (we can probably still enable another ten rulesets) but it's a good start.
Also:
* Be explicit about used ruff subcommand in tox.ini
* Fix the settings path to current tool.ruff.lint
* As linting result: Fix one output bug
* Tweak some error handling cases and implement style suggestions
> Lint improvements

- signer/tuf_on_ci_sign/_signer_repository.py
* Include the actual failure message in output
* Provide stack trace in debug log
* Allow canceling
Combined with python-tuf main branch this now looks like 
```
$ tuf-on-ci-sign --no-push sign/test-signing-failures
Signing event sign/test-signing-failures (commit 7e6d238)
Your signature is requested for role(s) {'jku'}.
jku v5
* Removed artifact 'jku/file1'
Enter pin to sign: 
Failed to sign jku with @jku key.
Failed to sign: CKR_PIN_INCORRECT (0x000000A0)
Press any key to try again (Ctrl-C to cancel): 
```
Not amazing but I think much better than before
> signer: Improve failure handling during sign

- repo/tuf_on_ci/_repository.py
This is pretty specific workaround for Sigstore root-signing: The targetfile structure contains custom metadata that would be nice to preserve when the artifact list is re-generated.
Partially fixes #192 
---
There is no test for this (as tuf-on-ci just does not have a way to add this custom metadata) but I've tested it manually
> repo: Preserve custom fields in TargetFiles

- signer/tuf_on_ci_sign/_common.py
- signer/tuf_on_ci_sign/delegate.py
- signer/tuf_on_ci_sign/sign.py
Improve the non-maintainer signer flow 
* Use `push --force`  to avoid issues when contributing to same signing event multiple times
* Directly open a browser in the open-a-pull-request URL after non-maintainer signing
Fredrik tested this in https://github.com/jku/tuf-demo/pull/101
Fixes #207.
Fixes #208.
> Improve non-maintainer signer flow

- actions/test-repository/action.yml
- repo/tuf_on_ci/client.py
Add multiple optional arguments to the action
This one is for upgrade testing after a signing event:
* Add upgrade testing with `update_base_url`: this allows testing that the new repository is a compliant upgrade from an existing repository version. This is useful when we have a "prod" and "preprod" environments and a  new "preprod" deployment is being tested: in this case "prod" can be used as the `update_base_url`
All of the following are reasonable use cases from sigstore-probers (so out-of-tree testing for alerting purposes):
* Add `compare_source` option to allow running the test without being inside a tuf-on-ci repository (when 'false', the metadata versions are not verified to be specific ones)
* Add `metadata_dir` to allow using the client metadata for e.g. deduplication like …
> Test repository improvements

- signer/test/test_user.py
- signer/tuf_on_ci_sign/_signer_repository.py
- signer/tuf_on_ci_sign/_user.py
* Make sure we re-initialize the signer when trying to sign again after a failure (this makes sense if e.g. yubikey has been switched midsigning)
* verify the signature after signing
* Only cache signers after a successful signing
> signer: Increase signing robustness

- actions/create-signing-events/action.yml
- actions/online-sign/action.yml
- actions/signing-event/action.yml
- actions/test-repository/action.yml
This keeps the useful version information available but prevents the flooding.
> actions: Improve pip install output

- docs/CHANGELOG.md
- repo/tuf_on_ci/__init__.py
- signer/tuf_on_ci_sign/__init__.py
**Changes**
* actions: test-repository action has many additional features (#239)
* actions: python package versions are now in logs again (#247)
* signer: Improve signing robustness (#237)
* Dependency updates (including more strictly pinned securesystemslib)
> Release v0.9

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/update-pinned-deps.yml
- actions/create-signing-events/action.yml
- actions/online-sign/action.yml
- actions/signing-event/action.yml
- actions/test-repository/action.yml
- actions/upload-repository/action.yml
- build-constraints.txt
- tox.ini
* `requirements.txt` is rebuilt by running pip-compile on `repo/pyproject.toml`
* this build happens in a new workflow that runs once a week and creates a PR if something changed
* requirements.txt is used as a constraint when installing `repo/` within the actions
Some drawbacks of this approach:
* We're doing this manually like some kind of cavepeople: bugs are inevitable in 70 lines yaml
* The reason for doing it manually is that as far as I can tell dependabot cannot manage adding/removing indirect dependencies as needed. As a result the PR lacks all links and details that Dependabot PRs have
* We _could_ run this in addition to running Dependabot on requirements.txt: this way normal upgrades could be handled by dependabot and the caveman approach would be used for added/removed deps …
> Pin all the deps

- .github/dependabot.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/update-pinned-deps.yml
* Bump all python versions to 3.12
* Run tests in a matrix: this should look a lot nicer in GitHub
* Include "test-signer" that was missing so far
* Update the dependency file list for caching
* Add missing init file for tests
* Change dependabot settings
> workflow: Update CI workflow & dependabot config

- actions/test-repository/action.yml
If artifact URL is not given to test-repository, make a slightly better guess than before. This does something reasonable for both
* the default tuf-on-ci setup
* and the sigstore setup (where targets url is "inside" metadata url)
Previously the latter might end up with
ARTIFACT_URL="https://tuf-repo-cdn.sigstore.devtargets"
when the METADATA_URL does not end in a slash
Fixes #274
> actions: Guess a better artifact url

- .github/dependabot.yml
This is a public beta feature that should help with dependabot spam for the actions by combining all actions (and workflows) updates into one issue
https://github.blog/changelog/2024-04-29-dependabot-multi-directory-configuration-public-beta-now-available/
--- 
I'd like to try the beta since they're asking for feedback. We should see if it's working immediately as I'm also adding the last two actions so that will trigger some updates...
> Use dependabot beta features

- .github/dependabot.yml
It seems like *.txt files are found anywhere under the configured dependabot dir but pyproject.toml are found only in the configured dir itself.
Add separate configs to get updates to pyproject.tomls.
> dependabot: Bring back individual configs for signer/repo

- .github/workflows/update-pinned-deps.yml
The dependency update PR created in a custom workflow does not trigger tests: 
* this is because events do not trigger for PRs opened by GitHub actions default token
* WorkflowDispatch() would run the tests... but would not add the checkmark
Maintainers can workaround this issue with close+reopen: document that in the issue
> workflows: Add info to dependency update PR

- .github/dependabot.yml
The aim is to get dependabot to actually skip /repo/install/ because this is managed by update-pinned-deps.yml: Currently the pyproject-dependencies group will catch these deps as well and we don't want that.
If this does not work, we'll have to move the pinning file out of /repo/ completely.
> dependabot: Reorder pip entries

- .github/dependabot.yml
At least currently Dependabots new "directories" feature only creates one issue at a time (even if it should file multiple). I hope this grouping will at least include all of the changes in a single PR.
> dependabot: Group the actions updates

- repo/pyproject.toml
- signer/pyproject.toml
* signer already accidentally uses 3.1 API: upgrade both repo and signer
* Don't upgrade further because tuf 4-5 are incompatible with released sigstore
Fixes #300
> Upgrade tuf dependency

- signer/test/test_signer_repository.py
- signer/tuf_on_ci_sign/_signer_repository.py
- signer/tuf_on_ci_sign/delegate.py
- tests/expected/basic/metadata/1.root.json
- tests/expected/basic/metadata/1.targets.json
- tests/expected/delegated/metadata/1.delegated.json
- tests/expected/delegated/metadata/1.root.json
- tests/expected/delegated/metadata/2.targets.json
- tests/expected/multi-user-signing/metadata/1.root.json
- tests/expected/multi-user-signing/metadata/1.targets.json
- tests/expected/multi-user-signing/metadata/2.root.json
- tests/expected/online-version-bump/metadata/1.root.json
- tests/expected/online-version-bump/metadata/1.targets.json
- tests/expected/root-key-rotation/metadata/1.root.json
- tests/expected/root-key-rotation/metadata/1.targets.json
- tests/expected/root-key-rotation/metadata/2.root.json
- tests/expected/target-file-changes/metadata/1.root.json
- tests/expected/target-file-changes/metadata/3.targets.json
- tests/expected/target-files-in-delegated-roles/metadata/1.root.json
- tests/expected/target-files-in-delegated-roles/metadata/1.targets.json
- tests/expected/target-files-in-delegated-roles/metadata/2.delegated.json
Spec demands that keyids be calculated from the keys canonicalized json. This is not that useful and it is a bit of a pain in the butt so most clients don't bother... but it is in the spec.
Make sure the keyids we generate are compliant.
> signer: Make sure initial keyid is spec-compliant

- actions/test-repository/action.yml
- repo/tuf_on_ci/client.py
Previously setting the initial root would only work if compare_source was False (because compare_source would lead to a checkout that would clean the initial root.json that had been put into working dir).
* Change tuf-on-ci-test-client so that --compare-source has an argument (the metadata directory to compare against)
* Checkout into a subdirectory: this allows root.json to exist in workdir
* Pass the metadata directory to tuf-on-ci-test-client --compare-source
This changes tuf-on-ci-test-client CLI but does not change the action API so existing users are fine.
Fixes #345
> actions: Fix test-repository source comparison

- repo/tuf_on_ci/_repository.py
Using snapshot contents is incorrect as snapshot is allowed to contain files that are no longer needed.
Fixes #342
> repo: Use delegation tree to decide which metadata to include in publishing

- signer/tuf_on_ci_sign/_signer_repository.py
- signer/tuf_on_ci_sign/delegate.py
- signer/tuf_on_ci_sign/import_repo.py
Fixes #336 , relates to #292 
This change will ensure that a a keyid fix can be done in a single signing event
* Make sure signing works with multiple keys (the UI for identifying which key is used isn't there yet but that's ok since so far this will only be used for the non-compliant keyid fix where the actual signing key is the same one, just with two different keyids)
* Add a hidden `--force-compliant-keyids` flag to delegate: this will update all keyids in the role and will mark all affected delegations to be resigned
This approach (just switching the all keyids) looks surprising but  should be 100% spec compliant. Example:
* root v1 has one root signer with key A using non-compliant keyid _abcd_. The metadata signatures contains a sig from _abcd_
* `tuf-on-ci-delegate …
> Fix noncompliant keyids

- repo/tuf_on_ci/build_repository.py
Hopefully this link will stay relative so it works even when hosted outside GitHub Pages. Based on https://jku.github.io/tuf-on-ci-sigstore-test/metadata/ this is the case: Jekyll does not rewrite this to absolute links
Unfortunately the css link is still absolute but not fully qualified so the page will be unstyled when copied outside GitHub pages: but at least the links now work
Fixes #353
> repo: Use html inside markdown to get relative links

- repo/tuf_on_ci/_repository.py
- repo/tuf_on_ci/create_signing_events.py
- tests/e2e.sh
- tests/expected/signing-event-creation/metadata/1.root.json
- tests/expected/signing-event-creation/metadata/2.root.json
- tests/expected/signing-event-creation/metadata/2.targets.json
- tests/expected/signing-event-creation/metadata/3.snapshot.json
- tests/expected/signing-event-creation/metadata/timestamp.json
The versioned file in `metadata/root_history/` should get created when root.json is modified.
Also add a end to end test for create-signing-events.
Fixes #347
> repo: Handle root correctly in create-signing-events

- signer/tuf_on_ci_sign/import_repo.py
We only want to fix keyids when the import is actually possible (not when we're just printing out the import json template)
> signer: Fix keyid tweaking in import-repo

- repo/tuf_on_ci/client.py
The default value of 32 is too low for some TUF repositories.
> Increase the number of root rotations allowed during TUF refresh.

- actions/online-sign-targets/action.yml
- actions/online-sign/action.yml
- actions/signing-event/action.yml
- docs/DELEGATION-MANUAL.md
- repo/pyproject.toml
- repo/tuf_on_ci/__init__.py
- repo/tuf_on_ci/_repository.py
- repo/tuf_on_ci/online_sign.py
- repo/tuf_on_ci/signing_event.py
- signer/tuf_on_ci_sign/_signer_repository.py
- signer/tuf_on_ci_sign/delegate.py
- tests/e2e.sh
This is mainly done by modifying tuf-on-ci-delegate to accept an online key as a signer for delegations. This require some extra care when dealing with the signer's identity. Keyowner or online-uri is now used.
Tuf-on-ci-online-sign now supports an extra parameter --role. This is used to perform online signing with delegations.
Closes https://github.com/theupdateframework/tuf-on-ci/issues/75
> Added support for delegations using cloud KMS

- signer/test/test_user.py
- signer/tuf_on_ci_sign/_user.py
It seems harmless but useful to prefix usernames with @ if the username in configuration does not have the prefix already
> signer: Accept username without @ in config file

- repo/tuf_on_ci/_repository.py
The sigstore root-signing online key keyid was entered incorrectly: Add a workaround here so there is more time to fix the actual keyid.
Fixes #422
--- 
DRAFT while I am not sure of the actual key version
> repo: Add workaround for sigstore KMS keyid

- signer/tuf_on_ci_sign/_user.py
- signer/tuf_on_ci_sign/delegate.py
- tests/e2e.sh
Ensure user names are handled as lower case
signer names (GitHub usernames) are compared in quite a few places: Ensure that comparisons are case-insensitive by always processing lowercase names    
* When reading in signer configuration from .tuf-on-ci-sign.ini, convert to lower case
* When taking in signer names as input when modifying a delegation, convert to lower case
Use a capital letter in those two cases in e2e tests.
> Case insensitive username comparison

- signer/tuf_on_ci_sign/_user.py
Fixes #417
---
It's not great but best I could think of -- the alternative would be to print that after PIN input but I'm not sure that's better.
FYI @bobcallaway
> signer: Add a hint to do touch authentication

- actions/signing-event/action.yml
Fixes: https://github.com/theupdateframework/tuf-on-ci/issues/399
The assumption is that this endpoint is way (computationally) cheaper then the org/repo search endpoint.
During the list PR we provide the tip of the current branch, during signing events is very unlikely that the tip is part of another PR, so I would think the code 'as is' is safe for use.
Marking this as draft for now, as I want to run more tests to confirm that this does not trigger the secondary rate limit.
> Avoid using search, look up pr by current commit instead

- actions/upload-repository/action.yml
- actions/upload-repository/index.css
We used jekyll before: it has various issues and turned out to not be the right tool for the job -- I only used it since it was a GitHub maintained action.
* Use pandoc (as container step) instead
* Include a minimal CSS file to make the status page look like it's not still the 1980s
* Prepare by copying the css file to workdir (which the pandoc container has access to)
* Two separate build directories are now not needed (everything happens in "build/").
* The result is now full standalone: copying the html file around should break nothing 
Fixes #430.
Example in https://jku.github.io/tuf-demo/metadata/
> actions: Switch status html rendering to pandoc

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/update-pinned-deps.yml
- actions/create-signing-events/action.yml
- actions/online-sign-targets/action.yml
- actions/online-sign/action.yml
- actions/signing-event/action.yml
- actions/test-repository/action.yml
- actions/upload-repository/action.yml
This is not urgent in any way but good to do at some point (and doing it right after a release sounds like a good idea):
* Install Python 3.13 in all actions
* Use 3.13 in tests and other workflows (except signer tests where we also want 3.9)
> Bump repository and test Python version to 3.13

- .github/workflows/release.yml
- actions/upload-repository/action.yml
These do not seem like actual security issues in the context where they're used (the inputs are not necessarily user controlled here) but it is good form to avoid the "${{ }}" format in any actual scripts.
> Be more careful with GHA variable substitutions

- actions/signing-event/action.yml
Fixes: https://github.com/theupdateframework/tuf-on-ci/issues/517
> No closed prs

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .github/workflows/update-pinned-deps.yml
- actions/create-signing-events/action.yml
- actions/online-sign-targets/action.yml
- actions/online-sign/action.yml
- actions/signing-event/action.yml
- actions/test-repository/action.yml
- actions/upload-repository/action.yml
Reverts theupdateframework/tuf-on-ci#514
Can be merged again after we release 0.15.2
> Revert "Bump repository and test Python version to 3.13"

- signer/pyproject.toml
- signer/tuf_on_ci_sign/_signer_repository.py
There is now light infrastructure for handling PKCS errors... I'm only handling the one that seems to trip people up since there are so many possible errors: we can't possibly do a good job of handling all of them.
Couple of review notes:
* I can't directly test this one: The touch policy on a yubikey can only be set when the certificate is created and and the touch policy on my keys is the default "never" -- I'd have to overwrite my key or buy a new yubikey for this. I have tested the code by adding handling for another case (CKR_ARGUMENTS_BAD) and that works fine so I trust that this one works too
* I was a little surprised I have to access a private field (`e.__context__`) to get the original exception... but that seems the only way
Fixes #527
> signer: Handle the "yubikey auth required" case

- .github/workflows/update-pinned-deps.yml
The zizmor lint addition tightened the workflow token leaks: In this specific case we actually want to leak as we are pushing a branch.
It looks like zizmor does not complain about this now that we explicitly set the value to true.
> workflows: let update-pinned-deps have the token it needs

- .github/dependabot.yml
I didn't add zizmor to repo/pypproject.toml in #548 since it's not actually linting the python code. Instead I put in in actions/lint-requirements.txt. This means we have to include the actions/ repo in the dependendabot config to get the version updates.
> Include actions/ in dependabot lint tool update

- repo/tuf_on_ci/_repository.py
This fixes lint: securesystemslib annotations are now better but they also now make it clear the API is a bit bonkers so we need to workaround.
This should unblock the dependabot updates
> repo: Fix securesystemslib annotation issue

- actions/upload-repository/action.yml
* Dependabot apparently does not manage docker:// references
* The pandoc image has been updated and the old no longer exists
Update hash manually for now to unbreak things: I will file an issue to actually improve this somehow, this is not a reasonable way to update things.
> Update pandoc image reference
